//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kübra
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHATALAR
    {
        public int HATAID { get; set; }
        public string NUMARA { get; set; }
        public string MESAJ { get; set; }
        public System.DateTime ZAMANI { get; set; }
        public string PROSEDUR { get; set; }
    }
}
