//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kübra
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLILCELER
    {
        public int ID { get; set; }
        public string ILCE { get; set; }
        public int IL { get; set; }
    
        public virtual TBLILLER TBLILLER { get; set; }
    }
}
