//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kübra
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKASA
    {
        public int ID { get; set; }
        public Nullable<int> FATURAID { get; set; }
        public Nullable<int> GİDERID { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual TBLFATURADETAY TBLFATURADETAY { get; set; }
    }
}
